# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWjbyZiqCz7FiQsvbV_8gYYox2vifm7N
"""

!pip install ultralytics

from ultralytics import YOLO
import os
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path
from sklearn.model_selection import train_test_split

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/NTI - Project/VOC2028.zip"

#CONFIGURATION
CLASSES = {"hat": 0, "head": 1, "person": 2}  # Update with your actual class names
# POINT TO YOUR SEPARATE FOLDERS HERE
RAW_IMAGES_DIR = Path("/content/VOC2028/JPEGImages")
RAW_LABELS_DIR = Path("/content/VOC2028/Annotations")
OUTPUT_DIR = Path("yolo_ready_dataset")

def convert_xml_to_yolo(xml_path, img_w, img_h):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    yolo_lines = []

    for obj in root.findall("object"):
        name = obj.find("name").text
        if name not in CLASSES: continue

        bnd = obj.find("bndbox")
        xmin = float(bnd.find("xmin").text)
        ymin = float(bnd.find("ymin").text)
        xmax = float(bnd.find("xmax").text)
        ymax = float(bnd.find("ymax").text)

        # The Math
        x_center = ((xmin + xmax) / 2) / img_w
        y_center = ((ymin + ymax) / 2) / img_h
        w = (xmax - xmin) / img_w
        h = (ymax - ymin) / img_h

        yolo_lines.append(f"{CLASSES[name]} {x_center} {y_center} {w} {h}")

    return yolo_lines

def process_dataset():
    # 1. Setup Directories
    for split in ['train', 'val']:
        (OUTPUT_DIR / split / 'images').mkdir(parents=True, exist_ok=True)
        (OUTPUT_DIR / split / 'labels').mkdir(parents=True, exist_ok=True)

    # 2. Get all images from the image directory
    images = list(RAW_IMAGES_DIR.glob("*.jpg")) + list(RAW_IMAGES_DIR.glob("*.png")) + list(RAW_IMAGES_DIR.glob("*.jpeg"))

    if not images:
        print("Error: No images found! Check RAW_IMAGES_DIR path.")
        return

    # 3. Split 80/20
    train_imgs, val_imgs = train_test_split(images, test_size=0.2, random_state=42)

    # 4. Process Loop
    for split, img_list in [('train', train_imgs), ('val', val_imgs)]:
        for img_path in img_list:


            xml_filename = img_path.stem + ".xml"
            xml_path = RAW_LABELS_DIR / xml_filename

            if not xml_path.exists():
                print(f"Skipping {img_path.name} - No matching XML found.")
                continue

            shutil.copy(img_path, OUTPUT_DIR / split / 'images' / img_path.name)

            # Convert Label
            try:
                tree = ET.parse(xml_path)
                size = tree.find("size")
                width = float(size.find("width").text)
                height = float(size.find("height").text)

                lines = convert_xml_to_yolo(xml_path, width, height)

                # Save Label
                label_path = OUTPUT_DIR / split / 'labels' / (img_path.stem + ".txt")
                with open(label_path, 'w') as f:
                    f.write('\n'.join(lines))
            except Exception as e:
                print(f"Error parsing {xml_path}: {e}")

    # 5. Create data.yaml automatically
    yaml_content = f"""
    path: {OUTPUT_DIR.absolute()}
    train: train/images
    val: val/images
    names: {list(CLASSES.keys())}
    """
    with open(OUTPUT_DIR / "data.yaml", "w") as f:
        f.write(yaml_content)

    print("Dataset Ready!")

# RUN EVERYTHING 
process_dataset()

#  TRAIN 
model = YOLO('yolov8n.pt')
model.train(data=str(OUTPUT_DIR / "data.yaml"), epochs=20, imgsz=640)

# EVALUATION FUNCTION 
def print_research_metrics(model_path, dataset_yaml, dataset_name):
    print(f"Evaluating {dataset_name} with {model_path}")
    model = YOLO(model_path)

    # Run validation
    metrics = model.val(data=dataset_yaml, verbose=False)

    # Extract key numbers
    map50 = metrics.box.map50
    map50_95 = metrics.box.map
    precision = metrics.box.mp
    recall = metrics.box.mr

    print(f"mAP@50 (Accuracy):      {map50:.3f}")
    print(f"mAP@50-95 (Precision):  {map50_95:.3f}")
    print(f"Precision:              {precision:.3f}")
    print(f"Recall:                 {recall:.3f}")

    return map50

#  USE THIS IN YOUR MAIN BLOCK 
# 1. Evaluate Baseline on Dataset A (Source)
score_A = print_research_metrics(
    '/content/runs/detect/train/weights/best.pt',
    '/content/yolo_ready_dataset/data.yaml',
    'Dataset A (Source)'
)

# 2. Evaluate Baseline on Dataset B (Target - if you have it)
# score_B = print_research_metrics(...)

# 3. Calculate Drop (for your paper)
# drop = ((score_A - score_B) / score_A) * 100
# print(f"Performance Drop: {drop:.1f}%")

import cv2
import matplotlib.pyplot as plt
model = YOLO('runs/detect/train/weights/best.pt')
image_path = '/content/001437.jpg'
results = model.predict(source=image_path, conf=0.25)
result_img_bgr = results[0].plot()
result_img_rgb = cv2.cvtColor(result_img_bgr, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(10, 10))
plt.imshow(result_img_rgb)
plt.axis('off')
plt.show()

# Change conf from 0.25 to 0.01 (1%) to see EVERYTHING
results = model.predict(source='/content/blog-construction.jpg', conf=0.50, save=True)

# Plot it to see if faint boxes appear
import matplotlib.pyplot as plt
plt.imshow(results[0].plot())
plt.show()

